behaviors:
  AICustomer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 5000
      learning_rate: 1e-3
      beta: 1e-2
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000
    checkpoint_interval: 50000
    time_horizon: 64
    summary_freq: 10000
